#!/bin/bash

cd ${0%/*} || exit 1
set -x

wmake solvers/biofilmGrowthFoam
wmake solvers/dbsBiofilmPimpleFoam
wmake solvers/dbsPimpleFoam
wmake solvers/pimpleFoam

wmake utilities/inoculumGenerator
wmake utilities/parabolicVelocity
