#!/bin/bash

cd ${0%/*} || exit 1
set -x

# if [ -f $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments ]
# then  . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
# fi

wmake libraries

wmake solvers/biofilmFoam
wmake solvers/biofilmPimpleFoam

wmake utilities/biomass
wmake utilities/inoculumGenerator
wmake utilities/permeability
