#!/bin/bash

cd ${0%/*} || exit 1
set -x

wclean all libraries/
wclean all solvers/
wclean all utilities/

if [ "$1" = "--purge" ]
then

    rm -rf $FOAM_USER_LIBBIN/libNumericalMethods.so
    rm -rf $FOAM_USER_LIBBIN/libParabolicVelocity.so
    
    rm -f $FOAM_USER_APPBIN/biofilmFoam
    rm -f $FOAM_USER_APPBIN/biofilmPimpleFoam

    rm -f $FOAM_USER_APPBIN/biomass    
    rm -f $FOAM_USER_APPBIN/inoculumGenerator
    rm -f $FOAM_USER_APPBIN/permeability
fi
