#!/bin/bash

cd ${0%/*} || exit 1
set -x

wclean libraries/

wclean solvers/biofilmGrowthFoam
wclean solvers/biofilmGrowthPicardFoam
wclean solvers/dbsBiofilmPimpleFoam
wclean solvers/dbsPimpleFoam

wclean utilities/inoculumGenerator
wclean utilities/parabolicVelocity
wclean utilities/permeability

if [ "$1" = "--purge" ]
then
    rm -f $FOAM_USER_APPBIN/biofilmGrowthFoam
    rm -f $FOAM_USER_APPBIN/biofilmGrowthPicardFoam
    rm -f $FOAM_USER_APPBIN/dbsBiofilmPimpleFoam
    rm -f $FOAM_USER_APPBIN/dbsPimpleFoam
    
    rm -f $FOAM_USER_APPBIN/inoculumGenerator
    rm -f $FOAM_USER_LIBBIN/libparabolicVelocity.so
    rm -f $FOAM_USER_LIBBIN/permeability
fi
