#!/bin/bash

cd ${0%/*} || exit 1
set -x

wclean libraries/

wclean solvers/biofilmFoam
wclean solvers/biofilmPicardFoam
wclean solvers/biofilmPimpleFoam

wclean utilities/biomass
wclean utilities/inoculumGenerator
wclean utilities/parabolicVelocity
wclean utilities/permeability

if [ "$1" = "--purge" ]
then
    rm -f $FOAM_USER_APPBIN/biofilmFoam
    rm -f $FOAM_USER_APPBIN/biofilmPicardFoam
    rm -f $FOAM_USER_APPBIN/biofilmPimpleFoam

    rm -f $FOAM_USER_APPBIN/biomass    
    rm -f $FOAM_USER_APPBIN/inoculumGenerator
    rm -f $FOAM_USER_LIBBIN/libparabolicVelocity.so
    rm -f $FOAM_USER_LIBBIN/permeability
fi
