#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

app=dbsBiofilmPimpleFoam

cp 0/porosity.org 0/porosity
cp 0/M.org 0/M

runApplication blockMesh
runApplication snappyHexMesh -overwrite

runApplication transformPoints -scale 1.89e-6

runApplication inoculumGenerator -patch sphere1 -nbcells 300
mv log.inoculumGenerator log.inoculumGenerator.sphere1
runApplication topoSet
mv log.topoSet log.topoSet.sphere1
runApplication setFields
mv log.setFields log.setFields.sphere1

runApplication inoculumGenerator -patch sphere2 -nbcells 300
mv log.inoculumGenerator log.inoculumGenerator.sphere2
runApplication topoSet
mv log.topoSet log.topoSet.sphere2
runApplication setFields
mv log.setFields log.setFields.sphere2

runApplication decomposePar
runParallel $app

#runApplication $app
