#!/bin/bash

. $WM_PROJECT_DIR/bin/tools/RunFunctions

app=dbsBiofilmPimpleFoam

cp 0/porosity.org 0/porosity
cp 0/M.org 0/M
runApplication blockMesh

runApplication inoculumGenerator -patch bottom -nbcells 64
mv log.inoculumGenerator log.inoculumGenerator.1
runApplication topoSet
mv log.topoSet log.topoSet.1
runApplication setFields
mv log.setFields log.setFields.1

runApplication inoculumGenerator -patch top -nbcells 64
mv log.inoculumGenerator log.inoculumGenerator.2
runApplication topoSet
mv log.topoSet log.topoSet.2
runApplication setFields
mv log.setFields log.setFields.2

runApplication $app
